sudo: false

language: bash

script:
  - bash -x -e < <(curl -kL https://github.com/phuslu/goproxy/raw/master/assets/scripts/ci.sh)

branches:
  only:
    - master

addons:
  apt:
    packages:
      - p7zip-full

notifications:
  email:
    recipients:
      - phuslu@hotmail.com
    on_success: change
    on_failure: change
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/d5a20bb0bd02e240904f
    on_success: always
    on_failure: always
    on_start: always
