dist: trusty
sudo: false

language: bash

script:
  - cd /tmp
  - bash -xe < <(curl -kL https://github.com/phuslu/goproxy/raw/master/assets/build/ci.sh)

branches:
  only:
    - master

addons:
  apt:
    packages:
      - g++-mingw-w64
      - gcc-4.8-multilib-arm-linux-gnueabihf
      - gcc-arm-linux-gnueabihf
      - lftp
      - libc6-dev-armhf-cross
      - p7zip-full
